# Site settings
title: PhD. Roben Castagna Lunardi
email: roben.lunardi at restinga.ifrs.edu.br
description: Personal webpage of Roben C. Lunardi
baseurl: ""
url: "https://robenlunardi.github.io"
affiliation: I am part of the  SciFi group at IFRS  - Campus Restinga.

# Google analytics ID
# google_analytics: G-XXXXXXXX

# Location info. (shown in footer)
location: >
  Instituto Federal de Educação, Ciência e Tecnologia - Campus Restinga<br/>
  Alberto Hoffmann, 285<br/>
  91791-508 - Porto Alegre/RS<br/>
  Brazil<br/>

# Contact info. (shown in footer)
contact: >
    Contact me via email: roben.lunardi at restinga.ifrs.edu.br<br/>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: publications
  - name: talks
  - name: research \& projects
  - name: software
  # - name: team
  - name: education
  # - name: volunteering

# Do you want to group your publications by year? {true/false}
group_pub_by_year: true

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
